name: Rebuild

on: push
    
  # push: {branches: [main]}
  # run automatically in schedule
  # schedule: [{cron: "12 12 * * *"}]
  # workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  rebuild-project:
    runs-on: ubuntu-latest

    steps:

    - name: checkout repo content
      uses: actions/checkout@v4

    - name: Install gdal
      run: |
        sudo apt-get -y install gdal-bin
        which ogr2ogr
        ogr2ogr --version

    - name: Run script
      run: |
        echo "Running script..."
        chmod +x ./load-and-transform-data.sh
        ./load-and-transform-data.sh
        
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4